document.querySelector("#backarrow").innerHTML += BackArrowUI("frame9.html")
document.querySelector(".downarrow").innerHTML += DownArrowUI()
document.querySelector("#whitebg").innerHTML += whiteUI()
document.querySelector("#anorexiapie").innerHTML += AnorexiaPieUI()
document.querySelector(".downarrow1").innerHTML += DownArrowUI()
document.querySelector("#woman").innerHTML += ManAndWomanUI()
document.querySelector('#backbutton').innerHTML += backButton("GO BACK", "frame9.html")
document.querySelector('#seekhelp').innerHTML += backButton("SEEK HELP","Frame16.html")