document.querySelector("#heading").innerHTML += HeaderText("#26325B","Helpline")
document.querySelector("#doctor").innerHTML += DoctorsUI()
document.querySelector("#doctor").innerHTML += DoctorsUI("https://placekitten.com/100/100", "Richmond Eating Disorders", "8100 Granville Ave, Richmond, BC V6Y 3T6", "#E79A74")
document.querySelector("#doctor").innerHTML += DoctorsUI("https://placekitten.com/200/200", "Min's Eating Disorders", "1300 Oakridge Ave, Vancouver, BC V6Y 3T6", "#C4C4C4")
document.querySelector('#pinkbutton').innerHTML += pinkButton("START OVER", "frame9.html")
document.querySelector("#backarrow").innerHTML += BackArrowUI()
