document.querySelector("#heading").innerHTML += HeaderText("Have you experienced any of these symptopms?")
document.querySelector("#whitebg").innerHTML += whiteUI()
document.querySelector("#yesbutton").innerHTML += NoButtonUI("Yes")
document.querySelector("#nobutton").innerHTML += NoButtonUI()
document.querySelector("#backarrow").innerHTML += BackArrowUI()
document.querySelector('#main').innerHTML += smileItem()