document.querySelector("#heading").innerHTML += HeaderText("Have you experienced any of these symptoms?")
document.querySelector("#whitebg").innerHTML += whiteUI(" • Regularly eat too much food <br> •  Swollen salivary glands <br>(by neck and jaw)  <br> •  Extreme thinness <br> • Reflux disorder/other gastrointestinal problems <br> • Severe dehydration <br> • Electrolyte imbalance", "1.4")
document.querySelector("#yesbutton").innerHTML += NoButtonUI("Yes")
document.querySelector("#nobutton").innerHTML += NoButtonUI()
document.querySelector("#backarrow").innerHTML += BackArrowUI()
document.querySelector('#smile').innerHTML += smileItem()