document.querySelector("#heading").innerHTML += HeaderText("#26325B","Have you experienced any of these symptoms?")
document.querySelector("#whitebg").innerHTML += whiteUI()
document.querySelector("#yesbutton").innerHTML += NoButtonUI("Yes")
document.querySelector("#nobutton").innerHTML += NoButtonUI()
document.querySelector("#backarrow").innerHTML += BackArrowUI("Frame10.html")
document.querySelector('#smile').innerHTML += smileItem()