document.querySelector("#backarrow").innerHTML += BackArrowUI("frame9.html")
document.querySelector(".downarrow").innerHTML += DownArrowUI()
document.querySelector("#whitebg").innerHTML += whiteUI(" • Stressful transitions or life changes <br> • History of abuse or trauma <br> • Negative body image <br> • Poor self-esteem", lineheight="2")
document.querySelector("#bullimiapie").innerHTML +=BulimiaPieUI()
document.querySelector(".downarrow1").innerHTML += DownArrowUI()
document.querySelector("#man").innerHTML += ManAndWomanUI("10%", "of the cases", "are males", "", "./imgs/man.png")
document.querySelector('#backbutton').innerHTML += backButton("GO BACK", "frame9.html")
document.querySelector('#seekhelp').innerHTML += backButton("SEEK HELP","Frame.html")