document.querySelector("#heading").innerHTML += HeaderText("Have you experienced any of these symptoms?")
document.querySelector("#whitebg").innerHTML += whiteUI(" • Chronically inflamed and sore throat  <br> •  Swollen salivary glands (by neck and jaw)  <br> •  Extreme thinness <br> • Reflux disorder/other gastrointestinal problems <br> • ")
document.querySelector("#yesbutton").innerHTML += NoButtonUI("Yes")
document.querySelector("#nobutton").innerHTML += NoButtonUI()
document.querySelector("#backarrow").innerHTML += BackArrowUI()
document.querySelector('#smile').innerHTML += smileItem()