document.querySelector("#heading").innerHTML += HeaderText("Helpline")
document.querySelector("#doctor").innerHTML += DoctorsUI()
document.querySelector("#doctor").innerHTML += DoctorsUI("https://placekitten.com/100/100", "Richmond Eating Disorders", "#E79A74")
document.querySelector("#doctor").innerHTML += DoctorsUI()
document.querySelector('#pinkbutton').innerHTML += pinkButton()
document.querySelector("#backarrow").innerHTML += BackArrowUI()
