document.querySelector("#heading").innerHTML += HeaderText("Helpline")
document.querySelector("#doctor").innerHTML += DoctorsUI()
document.querySelector("#doctor").innerHTML += DoctorsUI("https://placekitten.com/100/100", "Richmond Eating Disorders", "8100 Granville Ave, Rchmond, BC V6Y 3T6", "#E79A74")
document.querySelector("#doctor").innerHTML += DoctorsUI("https://placekitten.com/200/200", "Min's Eating Disorders", "8100 Granville Ave, Rchmond, BC V6Y 3T6", "#E79A74")
document.querySelector('#pinkbutton').innerHTML += pinkButton()
document.querySelector("#backarrow").innerHTML += BackArrowUI()
