document.querySelector("#heading").innerHTML += HeaderText("Helpline")
document.querySelector("#doctor").innerHTML += DoctorsUI()
document.querySelector("#doctor").innerHTML += DoctorsUI()
document.querySelector("#doctor").innerHTML += DoctorsUI()
document.querySelector('#pinkButton').innerHTML += pinkButton()
document.querySelector("#backarrow").innerHTML += BackArrowUI()
